const developers = [
  {
    id: 1,
    name: "Ananya Sharma",
    age: 23,
    role: "Frontend Developer",
    company: "@ TechNova Labs",
    location: "Bangalore, India",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&auto=format&fit=crop&q=80",
    bio: "Building delightful UIs and seamless experiences. Love open source and hackathons! 🚀🎨",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Framer Motion"],
    connections: 128,
    projects: 24,
    github: "ananya-sharma",
    hackathons: 8,
    verified: true,
    openToOpportunities: true,
  },
  {
    id: 2,
    name: "Arjun Sharma",
    age: 24,
    role: "Full Stack Developer",
    company: "@ TechVerse Solutions",
    location: "Bangalore, India",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80",
    bio: "Building scalable web apps and exploring new tech. Open to collaborate on exciting ideas!",
    skills: ["React", "Node.js", "TypeScript", "MongoDB"],
    connections: 128,
    projects: 3,
    github: "arjun-sharma",
    hackathons: 9,
    verified: true,
    openToOpportunities: false,
  },
  {
    id: 3,
    name: "Rohit Verma",
    age: 26,
    role: "Backend Engineer",
    company: "@ Infosys",
    location: "Hyderabad, India",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&auto=format&fit=crop&q=80",
    bio: "Node.js enthusiast building high-performance APIs and microservices at scale.",
    skills: ["Node.js", "Express", "MongoDB", "Redis", "Docker"],
    connections: 710,
    projects: 37,
    github: "rohit-verma",
    hackathons: 14,
    verified: true,
    openToOpportunities: true,
  },
  {
    id: 4,
    name: "Priya Patel",
    age: 25,
    role: "UI/UX Designer",
    company: "@ Adobe",
    location: "Mumbai, India",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&auto=format&fit=crop&q=80",
    bio: "Designing products that people love. Obsessed with clean design systems.",
    skills: ["Figma", "UI", "UX", "Prototyping", "Illustrator"],
    connections: 321,
    projects: 18,
    github: "priya-patel",
    hackathons: 6,
    verified: false,
    openToOpportunities: true,
  },
  {
    id: 5,
    name: "Sophia Brown",
    age: 27,
    role: "AI / ML Engineer",
    company: "@ Google DeepMind",
    location: "Mumbai, India",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&auto=format&fit=crop&q=80",
    bio: "Training models, deploying AI systems, and drinking too much coffee ☕.",
    skills: ["Python", "TensorFlow", "PyTorch", "FastAPI", "AWS"],
    connections: 855,
    projects: 42,
    github: "sophia-brown",
    hackathons: 15,
    verified: true,
    openToOpportunities: false,
  },
  {
    id: 6,
    name: "Michael Scott",
    age: 29,
    role: "DevOps Engineer",
    company: "@ AWS",
    location: "Delhi, India",
    image: "https://images.unsplash.com/photo-1504593811423-6dd665756598?w=800&auto=format&fit=crop&q=80",
    bio: "Automating everything with Docker, Kubernetes and CI/CD pipelines.",
    skills: ["Docker", "Kubernetes", "AWS", "Terraform", "Jenkins"],
    connections: 390,
    projects: 24,
    github: "michael-scott",
    hackathons: 5,
    verified: false,
    openToOpportunities: true,
  },
  {
    id: 7,
    name: "Meera Iyer",
    age: 24,
    role: "React Native Developer",
    company: "@ Swiggy",
    location: "Bangalore, India",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&auto=format&fit=crop&q=80",
    bio: "Crafting buttery-smooth mobile experiences. React Native + Expo enthusiast.",
    skills: ["React Native", "Expo", "Redux", "Firebase", "TypeScript"],
    connections: 275,
    projects: 15,
    github: "meera-iyer",
    hackathons: 7,
    verified: true,
    openToOpportunities: true,
  },
  {
    id: 8,
    name: "Vikram Singh",
    age: 28,
    role: "Blockchain Developer",
    company: "@ Polygon",
    location: "Pune, India",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80",
    bio: "Building the decentralized future. Solidity, DeFi and Web3 all day.",
    skills: ["Solidity", "Ethereum", "Web3.js", "Hardhat", "React"],
    connections: 492,
    projects: 19,
    github: "vikram-singh",
    hackathons: 12,
    verified: true,
    openToOpportunities: false,
  },
];

export default developers;